version: "3.8"

services:
  fastapi_app:
    build: .
    container_name: fastapi_app
    expose:
      - 8000  # Expose port 8000 to the Nginx container
    ports:
      - "8000:8000"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"  # Expose Nginx on port 80
    depends_on:
      - fastapi_app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge