name: test

on:
  push:
    branches:
      - main  # You can change this to any branch you want to trigger the CI pipeline

jobs:
  build:
    runs-on: ubuntu-latest  # Set the environment for the CI process

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Checkout the code from GitHub repository

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"  # Specify the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install all dependencies from the requirements file

      - name: Run Tests
        run: |
          pytest  # Run your tests (you can modify it to run any other test framework you're using)

      - name: Linting Check
        run: |
          flake8 .  # Run linting checks to make sure your code follows best practices
